version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: calculator_server
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./build/web:/var/www/html
